function net = cnn_cifar_init(opts)

lr = [.1 2] ;

% Define network CIFAR10-quick
net.layers = {} ;

% Block 1
net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{0.01*randn(5,5,3,64, 'single'), zeros(1, 64, 'single')}}, ...
                           'learningRate', lr*0.09, ...
                           'stride', 1, ...
                           'pad', 2) ;
net.layers{end+1} = struct('type', 'relu') ;
net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'avg', ...
                           'pool', [2 2], ...
                           'stride', 2, ...
                           'pad', [0 1 0 1]) ;

net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{0.01*randn(16,16,64,10, 'single'), zeros(1, 10, 'single')}}, ...
                           'learningRate', lr*0.09, ...
                           'stride', 1, ...
                           'pad', 0) ;


% Loss layer
net.layers{end+1} = struct('type', 'softmaxloss') ;